# Generated by mc: 15:41 4.14.2015.
#
	.data
	.text
g:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -40		# allocate locals
	li	$v0, 6
	sw	$v0, -24($fp)
	li	$v0, 4
	sw	$v0, -36($fp)
	li	$v0, 2
	sw	$v0, -32($fp)
	lw	$t1, -32($fp)
	lw	$t2, -36($fp)
	add	$v0, $t1, $t2
	sw	$v0, -28($fp)
	lw	$v0, -28($fp)
	sw	$v0, -20($fp)
	lw	$t1, -20($fp)
	lw	$t2, -24($fp)
	add	$v0, $t1, $t2
	sw	$v0, -16($fp)
	lw	$v0, -16($fp)
	sw	$v0, -12($fp)
	lw	$v0, -12($fp)
	sw	$v0, 12($fp)
	lw	$t1, 12($fp)
	lw	$t2, 8($fp)
	add	$v0, $t1, $t2
	sw	$v0, -8($fp)
	lw	$v0, -8($fp)
	sw	$v0, -4($fp)
	lw	$v0, -4($fp)
	move	$sp, $fp
	jr	$ra				# return
f:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -88		# allocate locals
	li	$v0, 6
	sw	$v0, -72($fp)
	li	$v0, 4
	sw	$v0, -84($fp)
	li	$v0, 2
	sw	$v0, -80($fp)
	lw	$t1, -80($fp)
	lw	$t2, -84($fp)
	add	$v0, $t1, $t2
	sw	$v0, -76($fp)
	lw	$v0, -76($fp)
	sw	$v0, -68($fp)
	lw	$t1, -68($fp)
	lw	$t2, -72($fp)
	add	$v0, $t1, $t2
	sw	$v0, -64($fp)
	lw	$v0, -64($fp)
	sw	$v0, -60($fp)
	lw	$v0, -60($fp)
	sw	$v0, 12($fp)
	li	$v0, 10
	sw	$v0, -56($fp)
	li	$v0, 6
	sw	$v0, -52($fp)
	lw	$t1, -52($fp)
	lw	$t2, -56($fp)
	mul	$v0, $t1, $t2
	sw	$v0, -48($fp)
	lw	$v0, -48($fp)
	sw	$v0, -28($fp)
	li	$v0, 8
	sw	$v0, -44($fp)
	li	$v0, 4
	sw	$v0, -40($fp)
	lw	$t1, -40($fp)
	lw	$t2, -44($fp)
	mul	$v0, $t1, $t2
	sw	$v0, -36($fp)
	lw	$v0, -36($fp)
	sw	$v0, -32($fp)
	lw	$t1, -32($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, -28($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push ra
	sw	$ra, 0($sp)
	jal	g				# funcall
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 8		# deallocate args
	sw	$v0, -24($fp)
	lw	$v0, -24($fp)
	sw	$v0, -20($fp)
	lw	$v0, -20($fp)
	sw	$v0, 8($fp)
	li	$v0, 2
	sw	$v0, -16($fp)
	li	$v0, 2
	sw	$v0, -12($fp)
	lw	$t1, -12($fp)
	lw	$t2, -16($fp)
	add	$v0, $t1, $t2
	sw	$v0, -8($fp)
	lw	$v0, -8($fp)
	sw	$v0, -4($fp)
	lw	$v0, -4($fp)
	sw	$v0, 12($fp)
